import consola from "consola";
import Manifest from "./Manifest";
import { input, confirm } from "@inquirer/prompts";
import path from "path";
import { mkdir, readFile, writeFile } from "fs/promises";
import Util from "./Util";

export default class Dialog {
    private manifest = new Manifest();
    private name: string;
    private cancel = false;
    private simpleForm: boolean;
    private beginButton: boolean;
    private endButton: boolean;

    public async add() {
        await this.prompt();

        if (!this.cancel) {
            await this.addDialog();
        }
    }

    private async prompt() {
        try {
            this.name = await this.getName();
            this.simpleForm = await this.addSimpleForm();
            this.beginButton = await this.addBeginButton();
            this.endButton = await this.addEndButton();
        } catch (error) {
            this.cancel = true;

            if (error instanceof Error && error.name === "ExitPromptError") {
                consola.info("Dialog generator has been canceled!");
            } else {
                throw error;
            }
        }
    }

    private async getName() {
        return input({
            message: "Enter a name for your SAPUI5 XML fragment (without .fragment.xml). Use dot notation for subfolders from the webapp folder:",
            required: true,
            validate: (value) => {
                const regex = /^([A-Za-z][A-Za-z0-9_]*)(\.[A-Za-z][A-Za-z0-9_]*)*$/;

                if (!regex.test(value)) {
                    return "Invalid fragment name. Use dot-separated parts starting with letters (e.g., fragments.employee.NewEmployee).";
                }

                return true;
            }
        });
    }

    private async addDialog() {
        try {
            await this.manifest.check();
            consola.start("Generating the SAPUI5 XML fragment with Dialog...");

            const parts = this.name.split(".");
            const dialogName = `${parts[parts.length - 1]}.fragment.xml`;
            let targetDirectory = path.join(process.cwd(), "webapp");

            if (parts.length > 1) {
                targetDirectory = path.join(targetDirectory, ...parts.slice(0, -1));
                const exists = await Util.pathExists(targetDirectory);

                if (!exists) {
                    consola.info(`Generating ${parts.slice(0, -1).join("/")} directory...`);
                    await mkdir(targetDirectory, { recursive: true });
                }
            }

            const target = path.join(targetDirectory, dialogName);
            const templatePath = path.join(__dirname, "..", "..", "template", "fragment", "Template.dialog.xml.tpl");
            let template = await readFile(templatePath, "utf-8");
            template = this.injectBlocks(template);

            consola.info(`Generating ${dialogName} file...`);
            await writeFile(target, template);
            consola.success("UI5 Ultima has successfully generated the SAPUI5 XML fragment file with a Dialog!");
        } catch (error) {
            consola.error(error);
        }
    }

    private async addSimpleForm() {
        return confirm({
            message: "Would you like to add Simpleform to your Dialog? (default: Y):",
            default: true
        });
    }

    private async addBeginButton() {
        return confirm({
            message: "Would you like to add begin button to your Dialog? (default: Y)",
            default: true
        });
    }

    private async addEndButton() {
        return confirm({
            message: "Would you like to add end button to your Dialog? (default: Y)",
            default: true
        });
    }

    private injectBlocks(content: string) {

        const simpleFormBlock = `
        <form:SimpleForm
            editable="true"
            columnsXL="1"
            columnsL="1"
            columnsM="1"
            labelSpanXL="12"
            labelSpanL="12"
            labelSpanM="12"
            labelSpanS="12"
            emptySpanXL="0"
            emptySpanL="0"
            emptySpanM="0"
            emptySpanS="0"
        >
            <form:content>
                <Label text="Generated by UI5 Ultima" />
                <Input/>
                <!-- form content here -->
            </form:content>
        </form:SimpleForm>
    `.trim();

        const beginButtonBlock = `
        <beginButton>
            <Button/>
        </beginButton>
    `.trim();

        const endButtonBlock = `
        <endButton>
            <Button/>
        </endButton>
    `.trim();

        const removeLine = (raw: string, placeholder: string) => {
            const lineRegex = new RegExp(
                `^[ \\t]*${placeholder}[ \\t]*\\r?\\n?`,
                "gm"
            );
            return raw.replace(lineRegex, "");
        };

        if (this.simpleForm) {
            content = content.replace("<!-- INSERT_NAMESPACES -->", `xmlns:form="sap.ui.layout.form"`);
            content = content.replace("<!-- INSERT_SIMPLEFORM -->", simpleFormBlock);
        } else {
            content = removeLine(content, "<!-- INSERT_NAMESPACES -->");
            content = removeLine(content, "<!-- INSERT_SIMPLEFORM -->");
        }

        if (this.beginButton) {
            content = content.replace("<!-- INSERT_BEGIN_BUTTON -->", beginButtonBlock);
        } else {
            content = removeLine(content, "<!-- INSERT_BEGIN_BUTTON -->");
        }

        if (this.endButton) {
            content = content.replace("<!-- INSERT_END_BUTTON -->", endButtonBlock);
        } else {
            content = removeLine(content, "<!-- INSERT_END_BUTTON -->");
        }

        return content;
    }
}