<core:FragmentDefinition
    xmlns="sap.m"
    xmlns:core="sap.ui.core"
    <!-- INSERT_NAMESPACES -->
>
    <Dialog>
        <Text text="Generated by UI5 Ultima" />
        <!-- INSERT_SIMPLEFORM -->
        <!-- INSERT_BEGIN_BUTTON -->
        <!-- INSERT_END_BUTTON -->
    </Dialog>
</core:FragmentDefinition>
