<mvc:View
    controllerName="{{NAMESPACE}}.controller.Main"
    displayBlock="true"
    xmlns="sap.m"
    xmlns:mvc="sap.ui.core.mvc"
    xmlns:core="sap.ui.core"
>
    <Page
        id="Main"
        showHeader="false"
    >
        <content>
            <Text text="Generated by UI5 Ultima" />
        </content>
    </Page>
</mvc:View>